# name: github actions
# on: push
# jobs:
#   actioon-jobs:
#     name: running action
#     runs-on: ubuntu-latest
#     steps:
#       - name: Action running
#         id: greet
#         uses: actions/hello-world-javascript-action@main
#         with:
#           who-to-greet: "Tayyab"
#       - name: Log Greeting Time
#         run: echo "${{steps.greet.outputs.time}}"

name: github actions
on: 
  push:
  pull_request:
    types: [opened,closed,assigned,reopened]
jobs:
  actioon-jobs:
    name: running action
    runs-on: ubuntu-latest
    steps:
      - name: Action running
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Tayyab"
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"
