# name: Super-Linter

# on: push

# jobs:
#   super-lint:
#     name: Lint code base
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
    
#     - name: Run Super-Linter
#       uses: github/super-linter@v3
#       env:
#         DEFAULT_BARNCH: main
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Shell script
on: push
jobs: 
    shell command :
        name: linux os
        runs-on: ubuntu-latest
        steps:
            - name: echo command running
              run: echo "Hello World"
            - name: multi line command
              run: |
                echo "Hello
                how are you 
                r u ok"
            - name: python shell
              run: |
                import platform
                print(platform.processor())
              shell: python
    windows command:
       name: windows os
       runs-on: windows-latest
       steps:
         - name: Directory Powershe
           run: Get-Location
         - name: Directory bash
           run: pwd
           shell: bash
    
